# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Mailing Address
    output: web, pdf
    folderitems:
    - title: Product 1 home
      url: /p1_landing_page.html
      output: web

    - title: Home Address
      url: /p1_sample1.html
      output: web, pdf

    - title: Phone
      url: /p1_sample2.html
      output: web, pdf

    - title: Direct Deposit
      url: /p1_sample3.html
      output: web, pdf

  - title: Address
    output: web, pdf

    folderitems:
    - title: Home
      url: /p1_sample4.html
      output: web, pdf

    - title: Mailing
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf
