# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Product2
  product: Product2
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:

    - title: Overview
      url: /p2_landing_page.html
      output: web

  - title: Home Address
    output: web, pdf
    folderitems:

    - title: Review Home Address
      url: /p2_sample1.html
      output: web, pdf

    - title: Modify Home Address
      url: /p2_sample2.html
      output: web, pdf

  - title: Mailing Address
    output: web, pdf
    folderitems:

    - title: Sample 6
      url: /p2_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p2_sample7.html
      output: web, pdf

    - title: Sample 8
      url: /p2_sample8.html
      output: web, pdf

    - title: Sample 9
      url: /p2_sample9.html
      output: web, pdf

    - title: Sample 10
      url: /p2_sample10.html
      output: web, pdf

    - title: Sample 11
      url: /p2_sample11.html
      output: web, pdf

    - title: Sample 12
      url: /p2_sample12.html
      output: web, pdf

    - title: Sample 13
      url: /p2_sample13.html
      output: web, pdf

    - title: Sample 14
      url: /p2_sample14.html
      output: web, pdf
